language: node_js
node_js:
    - 4
    - 5

script:
  - npm run codestyle
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false
